//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int ID { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public int Quantity { get; set; }
        public bool Isreturned { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> sallerid { get; set; }
        public Nullable<int> GST { get; set; }
        public string DeliveryStatus { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> DeliveryCharge { get; set; }
        public string InvoiceNumber { get; set; }
        public string PaymentMode { get; set; }
        public string ProductImage { get; set; }
        public Nullable<int> SellingPrice { get; set; }
        public Nullable<int> ListedPrice { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ReturnRequest { get; set; }
        public string RefundStatus { get; set; }
        public string DeliveryStatusOfReturn { get; set; }
        public Nullable<bool> IsConfirm { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public string Refundrequest { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
    }
}
