//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public int categoryId { get; set; }
        public Nullable<int> Discount { get; set; }
        public string Unit { get; set; }
        public Nullable<int> subcatid { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string cashback { get; set; }
        public string Cashbacktype { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> SelleroradminId { get; set; }
        public string Description { get; set; }
        public string BestSeller { get; set; }
        public string pincode { get; set; }
        public Nullable<decimal> DP { get; set; }
        public string Brandname { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> GST { get; set; }
        public string Dimentions { get; set; }
        public string Specification { get; set; }
        public Nullable<bool> active { get; set; }
        public string Type { get; set; }
        public string Weight { get; set; }
        public Nullable<bool> Sponserd { get; set; }
        public string productColor { get; set; }
        public Nullable<System.DateTime> Fromdate { get; set; }
        public Nullable<System.DateTime> Todate { get; set; }
        public Nullable<int> ApplyDiscount { get; set; }
        public string DiscountType { get; set; }
        public string AverageOrPercantage { get; set; }
        public string Copon { get; set; }
        public Nullable<bool> ApprovedByAdmin { get; set; }
        public string Image { get; set; }
        public Nullable<int> MRP { get; set; }
    }
}
