//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sallerDetail
    {
        public int sallerId { get; set; }
        public string FirstName { get; set; }
        public string SallerEmailId { get; set; }
        public string sallerContactNo { get; set; }
        public string ShopName { get; set; }
        public string ShopAddress { get; set; }
        public string Salerusername { get; set; }
        public string sallerpass { get; set; }
        public Nullable<bool> Active { get; set; }
        public string BussinessType { get; set; }
        public string BamkName { get; set; }
        public string IFSECode { get; set; }
        public string bankAddress { get; set; }
        public string BanificeryName { get; set; }
        public string AccountNumber { get; set; }
        public string DocumentType { get; set; }
        public string Document { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string PANno { get; set; }
        public string CINno { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
    }
}
