//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subcategory
    {
        public int id { get; set; }
        public Nullable<int> catid { get; set; }
        public string subcategorname { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> SelleroradminId { get; set; }
        public string ParentCategoryName { get; set; }
    }
}
