//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Order
    {
        public int ID { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string DeliveryStatus { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string OrderId { get; set; }
        public Nullable<int> Delivery_Charges { get; set; }
        public string CustomerUniqueID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerNumber { get; set; }
        public string ShippingAddress { get; set; }
        public string InvoiceNumber { get; set; }
        public string SellerUniqueID { get; set; }
        public Nullable<int> TotalOrderAmount { get; set; }
        public string PaymentMode { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Iscancelled { get; set; }
        public Nullable<bool> IsApprovedReturn { get; set; }
        public Nullable<int> sallerid { get; set; }
        public string Deleverydate { get; set; }
        public string Deleverytime { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string IsReturn { get; set; }
        public string IsConfirmed { get; set; }
    }
}
