//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_wallettrans
    {
        public int tran_id { get; set; }
        public Nullable<int> userid { get; set; }
        public string flag { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public string source { get; set; }
        public string providertranid { get; set; }
        public string sysgenid { get; set; }
        public string ipaddress { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string appname { get; set; }
        public string appversion { get; set; }
        public string timezone { get; set; }
        public string region { get; set; }
        public string city { get; set; }
        public string pincode { get; set; }
        public string countryname { get; set; }
        public string parymentgatewaytranid { get; set; }
        public string platform { get; set; }
    }
}
