//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_review
    {
        public int ID { get; set; }
        public string ProductID { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Productname { get; set; }
    }
}
