//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cashback
    {
        public int ID { get; set; }
        public Nullable<int> CientId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public string Unit { get; set; }
        public string Cashback { get; set; }
        public string cashbacktype { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> cashbackvalue { get; set; }
    }
}
