//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DeliveryCharge
    {
        public int ID { get; set; }
        public string Courier_Type { get; set; }
        public string Pincode { get; set; }
        public Nullable<decimal> From_Weight { get; set; }
        public Nullable<decimal> To_Weight { get; set; }
        public Nullable<decimal> Charge { get; set; }
    }
}
