//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public int UserId { get; set; }
        public string full_name { get; set; }
        public string gender { get; set; }
        public string mobilenumber { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string self_s_id { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public string ProfileImage { get; set; }
        public string Address { get; set; }
        public string DocType { get; set; }
        public string DocImage { get; set; }
        public string ShopName { get; set; }
        public string ShippingAddress { get; set; }
        public string DocumentNo { get; set; }
        public string Pincode { get; set; }
        public string State { get; set; }
        public string City { get; set; }
    }
}
