//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_checkout
    {
        public int Orderid { get; set; }
        public string Name { get; set; }
        public string Emailid { get; set; }
        public string Contactno { get; set; }
        public string Amount { get; set; }
    }
}
