//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_address
    {
        public int ID { get; set; }
        public string mainAddress { get; set; }
        public string AddLine2 { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string Statename { get; set; }
        public string City { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string DeliveryPersonName { get; set; }
        public string DeliveryPersonMOB { get; set; }
    }
}
